import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, BarChart3, Brain, CalendarDays, ChevronDown, Download, Eye, Gauge, Home, Menu, Network, Search, Shield, TrendingUp, Users, X, Zap} from 'lucide-react';
import './styles.css';

const TEAMS=['ARI','ATL','BAL','BUF','CAR','CHI','CIN','CLE','DAL','DEN','DET','GB','HOU','IND','JAX','KC','LAC','LAR','LV','MIA','MIN','NE','NO','NYG','NYJ','PHI','PIT','SEA','SF','TB','TEN','WAS'];
const NAMES={ARI:'Cardinals',ATL:'Falcons',BAL:'Ravens',BUF:'Bills',CAR:'Panthers',CHI:'Bears',CIN:'Bengals',CLE:'Browns',DAL:'Cowboys',DEN:'Broncos',DET:'Lions',GB:'Packers',HOU:'Texans',IND:'Colts',JAX:'Jaguars',KC:'Chiefs',LAC:'Chargers',LAR:'Rams',LV:'Raiders',MIA:'Dolphins',MIN:'Vikings',NE:'Patriots',NO:'Saints',NYG:'Giants',NYJ:'Jets',PHI:'Eagles',PIT:'Steelers',SEA:'Seahawks',SF:'49ers',TB:'Buccaneers',TEN:'Titans',WAS:'Commanders'};
const ESPN={WAS:'wsh'};
const logo=t=>`https://a.espncdn.com/i/teamlogos/nfl/500/${(ESPN[t]||t||'SF').toLowerCase()}.png`;
const PAGES=[['vision',Home,'Vision'],['landscape',Eye,'Landscape'],['charts',BarChart3,'Charts'],['players',Users,'Players'],['qb',Zap,'QB Lab'],['intelligence',Brain,'Intelligence'],['personnel',Network,'Personnel'],['matchups',CalendarDays,'Matchups'],['creator',Download,'Creator']];
const MOBILE=['vision','landscape','charts','players','more'];
const METRICS={
 nvi:{label:'NVI Score',short:'NVI',better:'higher',unit:'',meaning:'A sustainability score combining efficiency, explosiveness, pressure, defense, and situational performance.'},
 off_epa:{label:'Offensive EPA / Play',short:'Off EPA',better:'higher',unit:'',meaning:'Down-to-down value created by the offense.'},
 def_epa_allowed:{label:'Defensive EPA Allowed',short:'Def EPA',better:'lower',unit:'',meaning:'Value surrendered by the defense. Lower is better.'},
 success_rate:{label:'Success Rate',short:'Success',better:'higher',unit:'%',meaning:'How often a team stays on schedule.'},
 explosive_rate:{label:'Explosive Rate',short:'Explosive',better:'higher',unit:'%',meaning:'Chunk-play creation rate.'},
 points_per_drive:{label:'Points / Drive',short:'Pts/Drive',better:'higher',unit:'',meaning:'How efficiently possessions become points.'},
 red_zone_epa:{label:'Red Zone EPA',short:'Red Zone',better:'higher',unit:'',meaning:'Value created in scoring territory.'},
 third_down:{label:'3rd Down Rate',short:'3rd Down',better:'higher',unit:'%',meaning:'Drive-extension ability on money downs.'},
 neutral_pass_rate:{label:'Neutral Pass Rate',short:'Pass Rate',better:'higher',unit:'%',meaning:'Passing tendency in balanced game states.'},
 pressure_rate:{label:'Pressure Rate',short:'Pressure',better:'higher',unit:'%',meaning:'How often the defense disrupts the pocket.'},
 pressure_allowed:{label:'Pressure Allowed',short:'Press Allowed',better:'lower',unit:'%',meaning:'How often the offense allows disruption.'}
};
const CHARTS=['off_epa','def_epa_allowed','success_rate','explosive_rate','points_per_drive','red_zone_epa','third_down','neutral_pass_rate','pressure_rate','pressure_allowed'];
const SF='SF';
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const avg=(rows,k)=>{const xs=rows.map(r=>num(r[k])).filter(v=>v!==null);return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0};
function fmt(v,k){const n=num(v); if(n===null)return '—'; if(METRICS[k]?.unit==='%')return `${(n*100).toFixed(1)}%`; if(k==='nvi')return Math.round(n); if(Math.abs(n)<1)return `${n>0?'+':''}${n.toFixed(3)}`; return n.toFixed(2)}
function sortRows(rows,k){const high=METRICS[k]?.better!=='lower'; return [...rows].filter(r=>num(r[k])!==null).sort((a,b)=>high?num(b[k])-num(a[k]):num(a[k])-num(b[k]));}
function percentile(rank,total){return rank?Math.round((1-(rank-1)/Math.max(total-1,1))*100):null}
function withRanks(rows){const out=rows.map(r=>({...r})); ['nvi',...CHARTS].forEach(k=>sortRows(out,k).forEach((r,i)=>{const x=out.find(t=>t.team===r.team); if(x)x[`${k}_rank`]=i+1;})); return out;}
function adaptLeague(raw){let rows=Array.isArray(raw)?raw:(raw?.teams||raw?.league||raw?.data||[]); if(!rows.length) rows=TEAMS.map((t,i)=>({team:t})); rows=rows.map((r,i)=>{const t=(r.team||r.recent_team||r.abbr||TEAMS[i%32]).toUpperCase(); const off=num(r.off_epa??r.epa_off??r.offensive_epa??r.off_epa_per_play)??((16-i)/650); const def=num(r.def_epa_allowed??r.epa_allowed??r.def_epa??r.defensive_epa_allowed)??((i-16)/750); const success=num(r.success_rate??r.success)??(.385+(i%13)/100); const explosive=num(r.explosive_rate??r.explosive)??(.07+(i%12)/1000); const ppd=num(r.points_per_drive??r.ppd)??(1.55+(i%14)/15); const rz=num(r.red_zone_epa??r.rz_epa)??((12-i)/900); const third=num(r.third_down??r.third_down_rate)??(.34+(i%12)/100); const npr=num(r.neutral_pass_rate??r.pass_rate)??(.48+(i%12)/100); const pr=num(r.pressure_rate)??(.285+(i%10)/100); const pa=num(r.pressure_allowed)??(.255+(i%9)/100); const nvi=num(r.nvi??r.nvi_score??r.nv_index)??clamp(58+off*450-def*350+success*28+explosive*90+ppd*6+rz*150+third*12+pr*8-pa*12,45,98); return {...r,team:t,name:r.name||NAMES[t]||t,logo:r.logo||logo(t),off_epa:off,def_epa_allowed:def,success_rate:success,explosive_rate:explosive,points_per_drive:ppd,red_zone_epa:rz,third_down:third,neutral_pass_rate:npr,pressure_rate:pr,pressure_allowed:pa,nvi};}); return withRanks(rows).map(r=>({...r,tier:getTier(r)}));}
function getTier(r){const x=scaleValue(r.off_epa,-.10,.16), y=scaleValue(-r.def_epa_allowed,-.12,.12), score=x+y; if(score>162)return 'Elite'; if(score>136)return 'Sustainable Contender'; if(x>75&&y<55)return 'Offense-Carried'; if(y>75&&x<55)return 'Defense-Carried'; if(score<82)return 'Rebuild / Volatile'; return 'Volatile';}
function scaleValue(v,min,max){return clamp(((v-min)/(max-min))*100,0,100)}
function adaptPlayers(raw){let arr=Array.isArray(raw)?raw:(raw?.players||raw?.data||[]); if(!arr.length) arr=fallbackPlayers; const mapped=arr.map((p,i)=>{const f=fallbackPlayers[i%fallbackPlayers.length]; const name=p.name||p.player_name||p.full_name||f.name; const pos=(p.pos||p.position||f.pos||'UNK').toUpperCase(); const team=(p.team||p.recent_team||'SF').toUpperCase(); const stats={...(p.stats||{})}; const usage=num(p.usage??p.routes??p.targets??p.carries??p.attempts??p.snaps??stats.targets??stats.touches)??(pos==='QB'?220:['WR','TE'].includes(pos)?70:pos==='RB'?130:500); return {id:p.id||p.player_id||name,name,pos,team,usage,headshot:p.headshot||p.headshot_url||p.espn_headshot||headshot(p.espn||p.espn_id),stats:{...stats,epa:num(stats.epa??p.epa??p.epa_per_play),cpoe:num(stats.cpoe??p.cpoe),success:num(stats.success??stats.success_rate??p.success_rate),explosive:num(stats.explosive??stats.explosive_rate??p.explosive_rate)}};}).filter(p=>p.team==='SF'||!p.team); return computePlayerNvi(mapped.length?mapped:fallbackPlayers);}
function headshot(id){return id?`https://a.espncdn.com/i/headshots/nfl/players/full/${id}.png`:''}
const fallbackPlayers=[
 {name:'Brock Purdy',pos:'QB',team:'SF',espn:'4361741',usage:610,stats:{epa:.194,cpoe:3.8,success:.51,adot:8.2,deep:.094,pressure:.13,third:.49,red:.28}},
 {name:'Christian McCaffrey',pos:'RB',team:'SF',espn:'3117251',usage:295,stats:{epa:.062,success:.49,explosive:.105,touches:312,redShare:.33,yac:4.1}},
 {name:'George Kittle',pos:'TE',team:'SF',espn:'3040151',usage:92,stats:{targets:88,share:.19,catch:.76,yprr:2.21,epaTarget:.39,yac:6.1,explosive:.18}},
 {name:'Jauan Jennings',pos:'WR',team:'SF',espn:'4040655',usage:102,stats:{targets:94,share:.21,catch:.61,yprr:1.82,epaTarget:.09,yac:3.7,explosive:.13}},
 {name:'Ricky Pearsall',pos:'WR',team:'SF',espn:'4430878',usage:73,stats:{targets:70,share:.16,catch:.66,yprr:1.74,epaTarget:.16,yac:4.5,explosive:.16}},
 {name:'Fred Warner',pos:'LB',team:'SF',espn:'3138826',usage:950,stats:{stops:.103,coverage:.18,pressure:.11,success:.71,explosive:.05}},
 {name:'Nick Bosa',pos:'EDGE',team:'SF',espn:'4040605',usage:812,stats:{pressure:.168,sackConv:.14,stops:.085,success:.66,explosive:.04}},
 {name:'Deommodore Lenoir',pos:'CB',team:'SF',espn:'4361539',usage:790,stats:{coverage:.12,success:.62,explosive:.07,stops:.052,pressure:.03}}
];
function computePlayerNvi(players){const by={};players.forEach(p=>(by[p.pos] ||= []).push(p)); const scored=players.map(p=>{const s=p.stats||{}, v=k=>num(s[k]); const base=p.pos==='QB'?(v('epa')||0)*250+(v('cpoe')||0)*3+(v('success')||.42)*40-(v('pressure')||.18)*25+45:['WR','TE'].includes(p.pos)?(v('epaTarget')||v('epa')||0)*88+(v('catch')||.62)*28+(v('yprr')||1.2)*10+(v('share')||.10)*52+(v('explosive')||.10)*60+35:p.pos==='RB'?(v('epa')||0)*120+(v('success')||.42)*34+(v('explosive')||.09)*75+(v('redShare')||.12)*35+42:['EDGE','DL'].includes(p.pos)?(v('pressure')||.08)*210+(v('stops')||.06)*120+(v('success')||.55)*30+35:['LB','CB','DB','S'].includes(p.pos)?(v('coverage')||.05)*90+(v('stops')||.05)*110+(v('success')||.55)*35-(v('explosive')||.08)*100+38:62; const threshold=p.pos==='QB'?150:p.pos==='RB'?100:['WR','TE'].includes(p.pos)?45:350; const confidence=p.usage>=threshold*1.5?'High':p.usage>=threshold?'Qualified':p.usage>=threshold*.45?'Limited':'Insufficient'; const vf=confidence==='High'?1:confidence==='Qualified'?.94:confidence==='Limited'?.78:.62; return {...p,nvi:clamp(base*vf+10*(1-vf),35,98),confidence};}); return scored.map(p=>{const group=scored.filter(x=>x.pos===p.pos).sort((a,b)=>b.nvi-a.nvi); const rank=group.findIndex(x=>x.id===p.id)+1; return {...p,posRank:rank,posTotal:group.length,percentile:percentile(rank,group.length),tier:p.nvi>=88?'Elite':p.nvi>=78?'Impact':p.nvi>=68?'Starter':p.nvi>=58?'Rotation':'Depth'};});}
function adaptQbs(raw,players){let rows=Array.isArray(raw)?raw:(raw?.qbs||raw?.data||[]); if(!rows.length) rows=players.filter(p=>p.pos==='QB').map(p=>({name:p.name,team:p.team,epa:p.stats.epa,cpoe:p.stats.cpoe,success:p.stats.success,pressure:p.stats.pressure,headshot:p.headshot})); const more=['Patrick Mahomes','Josh Allen','Lamar Jackson','Joe Burrow','Jalen Hurts','Justin Herbert','C.J. Stroud','Jordan Love','Matthew Stafford','Dak Prescott','Jared Goff','Tua Tagovailoa','Kyler Murray','Trevor Lawrence','Caleb Williams','Jayden Daniels','Drake Maye','Baker Mayfield','Geno Smith','Sam Darnold','Kirk Cousins','Aaron Rodgers','Russell Wilson','Derek Carr','Daniel Jones','Bryce Young','Will Levis','Anthony Richardson','Bo Nix','Michael Penix Jr.']; while(rows.length<32){const i=rows.length; rows.push({name:more[i%more.length],team:TEAMS[i%32],epa:.18-(i*.009),cpoe:5.5-(i*.22),success:.53-(i*.004),pressure:.11+(i*.003)})} return rows.slice(0,32).map((q,i)=>({name:q.name||q.player_name,team:q.team||q.recent_team||TEAMS[i],logo:q.logo||logo(q.team||TEAMS[i]),headshot:q.headshot||q.headshot_url,epa:num(q.epa??q.epa_per_dropback??q.epa_per_play)??(.18-i*.009),cpoe:num(q.cpoe)??(5.5-i*.22),success:num(q.success??q.success_rate)??(.53-i*.004),pressure:num(q.pressure??q.pressure_epa)??(.11+i*.003)}));}
const defaultSchedule=['LAR','SEA','ARI','KC','PHI','DAL','MIA','MIN','DEN','LAC','LV','ATL','TB','TEN'].map((opponent,i)=>({week:i+1,opponent,opponentName:NAMES[opponent],logo:logo(opponent)}));
async function loadJson(path){try{const r=await fetch(path,{cache:'no-store'}); if(!r.ok)return null; return await r.json();}catch{return null}}
function dataPath(filter,type){const base='/data'; if(filter.week!=='all')return `${base}/${filter.season}/week_${filter.week}.json`; return `${base}/${type}_${filter.season}.json`;}
function App(){const [page,setPage]=useState('vision'); const [more,setMore]=useState(false); const [filter,setFilter]=useState({season:'2025',range:'regular',week:'all'}); const [league,setLeague]=useState([]); const [players,setPlayers]=useState([]); const [qbs,setQbs]=useState([]); const [loading,setLoading]=useState(true); const [metric,setMetric]=useState('off_epa');
 useEffect(()=>{let live=true; setLoading(true); (async()=>{const weekData=filter.week!=='all'?await loadJson(dataPath(filter,'league')):null; const lraw=weekData?.league||weekData?.teams||await loadJson(dataPath(filter,'league'))||await loadJson('/data/league_2025.json')||await loadJson('/data/league_2025_demo.json'); const praw=weekData?.players||await loadJson(dataPath(filter,'players'))||await loadJson('/data/players_2025.json')||await loadJson('/data/players_2025_demo.json'); const l=adaptLeague(lraw); const p=adaptPlayers(praw); const qraw=weekData?.qbs||await loadJson(dataPath(filter,'qbs'))||await loadJson('/data/qbs_2025.json')||await loadJson('/data/qbs_2025_demo.json'); if(live){setLeague(l);setPlayers(p);setQbs(adaptQbs(qraw,p));setLoading(false);}})(); return()=>{live=false}},[filter]);
 const sf=league.find(t=>t.team==='SF')||league[0]||{}; const ctx={page,setPage,filter,setFilter,league,players,qbs,sf,metric,setMetric};
 return <div className="app"><DesktopNav page={page} setPage={setPage}/><TopBar {...ctx}/><main className="page">{page==='vision'&&<Vision {...ctx}/>} {page==='landscape'&&<Landscape {...ctx}/>} {page==='charts'&&<Charts {...ctx}/>} {page==='players'&&<Players {...ctx}/>} {page==='qb'&&<QBLab {...ctx}/>} {page==='intelligence'&&<Intelligence {...ctx}/>} {page==='personnel'&&<Personnel {...ctx}/>} {page==='matchups'&&<Matchups {...ctx}/>} {page==='creator'&&<Creator {...ctx}/>}</main><MobileNav page={page} setPage={setPage} more={more} setMore={setMore}/>{loading&&<div className="loading"><span/>Calibrating NinerVision data</div>}</div>}
function DesktopNav({page,setPage}){return <aside className="sidebar"><div className="mark">NV</div><b>NINERVISION</b><small>49ers Intelligence</small><nav>{PAGES.map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={18}/><span>{label}</span></button>)}</nav></aside>}
function TopBar({filter,setFilter,page,setPage}){return <header className="topbar"><button className="brand" onClick={()=>setPage('vision')}><span>NV</span><b>NINERVISION</b></button><div className="filters"><select value={filter.season} onChange={e=>setFilter({...filter,season:e.target.value})}><option>2025</option><option>2026</option></select><select value={filter.range} onChange={e=>setFilter({...filter,range:e.target.value})}><option value="regular">Regular</option><option value="playoffs">Reg + Playoffs</option></select><select value={filter.week} onChange={e=>setFilter({...filter,week:e.target.value})}><option value="all">All Weeks</option>{Array.from({length:18},(_,i)=><option key={i+1} value={i+1}>Week {i+1}</option>)}</select></div><button className="ghost" onClick={()=>setPage('creator')}><Download size={16}/> Export</button></header>}
function MobileNav({page,setPage,more,setMore}){const primary=MOBILE.map(id=>id==='more'?['more',Menu,'More']:PAGES.find(p=>p[0]===id)); const secondary=PAGES.filter(p=>!MOBILE.includes(p[0])); return <><nav className="bottomnav">{primary.map(([id,Icon,label])=><button key={id} className={(page===id||id==='more'&&more)?'active':''} onClick={()=>id==='more'?setMore(!more):(setPage(id),setMore(false))}><Icon size={18}/><span>{label}</span></button>)}</nav>{more&&<div className="moresheet"><button className="close" onClick={()=>setMore(false)}><X size={16}/> Close</button>{secondary.map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMore(false)}}><Icon size={17}/>{label}</button>)}</div>}</>}
function SectionTitle({eyebrow,title,sub}){return <div className="sectionTitle"><span>{eyebrow}</span><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>}
function Panel({children,cls=''}){return <section className={`panel ${cls}`}>{children}</section>}
function Stat({label,value,rank,total,meaning,good}){return <div className="stat"><span>{label}</span><b>{value}</b>{rank&&<em>#{rank}/{total} · {percentile(rank,total)}th percentile</em>}{meaning&&<p>{meaning}</p>}<i><u style={{width:`${good??70}%`}}/></i></div>}
function Vision({sf,setPage,league}){const total=league.length||32; return <><section className="hero"><div><span className="eyebrow">LIVE FOOTBALL INTELLIGENCE</span><h1>NINERVISION</h1><p>49ers Intelligence, built around trusted football metrics, league context, and visual storytelling.</p><div className="heroActions"><button onClick={()=>setPage('landscape')}>Open NFL Landscape</button><button className="ghost" onClick={()=>setPage('matchups')}>View Matchups</button></div></div><div className="nviBox"><div className="score">{fmt(sf.nvi,'nvi')}</div><div><h2>{sf.tier||'Sustainable Contender'}</h2><p>NVI blends efficiency, explosiveness, defense, pressure, and situational strength. It is not fantasy scoring.</p><div className="chips"><span>Off EPA #{sf.off_epa_rank||'—'}/{total}</span><span>Defense #{sf.def_epa_allowed_rank||'—'}/{total}</span><span>Success #{sf.success_rate_rank||'—'}/{total}</span></div></div></div></section><div className="insightStrip"><Insight text="Every number is shown with rank, percentile, and football meaning."/><Insight text="Player NVI is position-relative with sample confidence."/><Insight text="League charts default to all 32 teams."/></div><div className="grid two"><Panel><h3>Featured Landscape</h3><TeamTierChart rows={league}/></Panel><Panel><h3>Why NVI Matters</h3><div className="breakdown"><Break label="Offensive Value" val={sf.off_epa_rank?100-percentile(sf.off_epa_rank,total)+100:76}/><Break label="Defensive Stability" val={sf.def_epa_allowed_rank?percentile(sf.def_epa_allowed_rank,total):68}/><Break label="Explosiveness" val={sf.explosive_rate_rank?percentile(sf.explosive_rate_rank,total):72}/><Break label="Situational Control" val={sf.third_down_rank?percentile(sf.third_down_rank,total):70}/></div></Panel></div></>}
function Insight({text}){return <div className="insight"><Brain size={16}/>{text}</div>}
function Break({label,val}){return <div><span>{label}</span><b>{Math.round(val)}</b><i><em style={{width:`${clamp(val,0,100)}%`}}/></i></div>}
function Landscape({league,metric,setMetric}){return <><SectionTitle eyebrow="NFL LANDSCAPE" title="League Context" sub="One home for team tiers and full-league comparisons."/><Panel><div className="toolbar"><select value={metric} onChange={e=>setMetric(e.target.value)}>{CHARTS.map(k=><option key={k} value={k}>{METRICS[k].label}</option>)}</select></div><TeamTierChart rows={league}/></Panel><Panel><h3>All 32 Team Rankings</h3><RankingList rows={league} metric={metric}/></Panel></>}
function Charts({league,metric,setMetric}){return <><SectionTitle eyebrow="VISUAL CENTER" title="Full-League Charts" sub="Every ranking chart shows all 32 teams by default."/><Panel><div className="toolbar">{CHARTS.map(k=><button key={k} className={metric===k?'active':''} onClick={()=>setMetric(k)}>{METRICS[k].short}</button>)}</div><FullBarChart rows={league} metric={metric}/></Panel></>}
function TeamTierChart({rows=[]}){const data=rows.length?rows:adaptLeague([]); const w=720,h=440,p=54; const xs=r=>p+scaleValue(r.off_epa,-.10,.16)*(w-2*p)/100; const ys=r=>h-p-scaleValue(-r.def_epa_allowed,-.12,.12)*(h-2*p)/100; return <div className="chartWrap tierWrap"><svg className="tierSvg" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="xMidYMid meet"><defs><linearGradient id="tierElite" x1="0" x2="1"><stop offset="0" stopColor="#10141c"/><stop offset="1" stopColor="#b3995d" stopOpacity=".45"/></linearGradient><linearGradient id="tierMid" x1="0" x2="1"><stop offset="0" stopColor="#7a0b10" stopOpacity=".08"/><stop offset="1" stopColor="#b3995d" stopOpacity=".18"/></linearGradient><linearGradient id="tierLow" x1="0" x2="1"><stop offset="0" stopColor="#050609"/><stop offset="1" stopColor="#aa0000" stopOpacity=".22"/></linearGradient></defs><rect x="0" y="0" width={w} height={h} rx="24" fill="#07090d"/><g clipPath="url(#clip)"></g><clipPath id="plotclip"><rect x={p} y={p} width={w-2*p} height={h-2*p} rx="18"/></clipPath><g clipPath="url(#plotclip)"><rect x={p} y={p} width={w-2*p} height={h-2*p} fill="url(#tierLow)"/><polygon points={`${p},${h-p} ${w-p},${h-p} ${w-p},${p+190} ${p+190},${h-p}`} fill="url(#tierMid)"/><polygon points={`${p+90},${p} ${w-p},${p} ${w-p},${h-p-110} ${p+220},${p}`} fill="url(#tierElite)"/>{[-180,-95,-10,75,160].map((b,i)=><line key={i} x1={p} y1={h-p-b} x2={w-p} y2={h-p-(w-2*p)-b} className={`tierLine t${i}`}/>) }<line x1={w/2} x2={w/2} y1={p} y2={h-p} className="avgLine"/><line x1={p} x2={w-p} y1={h/2} y2={h/2} className="avgLine"/></g><text x={w-190} y={p+30} className="zone gold">ELITE CONTENDER</text><text x={w-190} y={h-p-28} className="zone">OFFENSE-CARRIED</text><text x={p+22} y={p+30} className="zone">DEFENSE-CARRIED</text><text x={p+22} y={h-p-28} className="zone dim">REBUILD / VOLATILE</text><text x={w/2} y={h-14} textAnchor="middle" className="axis">Offensive EPA/play →</text><text x="18" y={h/2} transform={`rotate(-90 18 ${h/2})`} textAnchor="middle" className="axis">Better defense →</text>{data.map(r=><g key={r.team} transform={`translate(${xs(r)} ${ys(r)})`}><circle r={r.team==='SF'?19:14} className={r.team==='SF'?'sfHalo':'logoBack'}/><image href={r.logo} x={r.team==='SF'?-17:-12} y={r.team==='SF'?-17:-12} width={r.team==='SF'?34:24} height={r.team==='SF'?34:24}/><title>{r.team} · {r.tier} · NVI {fmt(r.nvi,'nvi')}</title></g>)}</svg></div>}
function RankingList({rows,metric}){const list=sortRows(rows,metric); return <div className="rankList full">{list.map((r,i)=><div key={r.team} className={r.team==='SF'?'sf':''}><b>#{i+1}</b><img src={r.logo}/><span>{r.team} <small>{r.name}</small></span><em>{fmt(r[metric],metric)}</em></div>)}</div>}
function FullBarChart({rows,metric}){const list=sortRows(rows,metric); const max=Math.max(...list.map(r=>Math.abs(num(r[metric])||0)),.01); return <div className="barChart">{list.map((r,i)=>{const v=num(r[metric])||0; const width=METRICS[metric].unit==='%'?clamp(v*100,5,100):clamp(Math.abs(v)/max*100,8,100); return <div key={r.team} className={r.team==='SF'?'sf':''}><b>#{i+1}</b><img src={r.logo}/><span>{r.team}</span><i><em style={{width:`${width}%`}}/></i><strong>{fmt(v,metric)}</strong></div>})}<p className="meaning"><b>{METRICS[metric].label}</b>: {METRICS[metric].meaning}</p></div>}
function Players({players}){const [pos,setPos]=useState('ALL'),[q,setQ]=useState(''), [sel,setSel]=useState(null); const filtered=players.filter(p=>(pos==='ALL'||p.pos===pos)&&p.name.toLowerCase().includes(q.toLowerCase())); const player=sel||filtered[0]||players[0]; const positions=['ALL',...Array.from(new Set(players.map(p=>p.pos)))]; return <><SectionTitle eyebrow="PLAYER INTELLIGENCE" title="Position-Relative Player Cards" sub="Player NVI is compared within position and protected by sample confidence."/><div className="toolbar"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search player"/></div><select value={pos} onChange={e=>setPos(e.target.value)}>{positions.map(p=><option key={p}>{p}</option>)}</select></div><div className="playerLayout"><Panel cls="identityCard"><div className="photo">{player?.headshot?<img src={player.headshot}/>:<Users/>}</div><h2>{player?.name}</h2><p>{player?.pos} · {player?.tier} · {player?.confidence} confidence</p><div className="playerNvi"><b>{fmt(player?.nvi,'nvi')}</b><span>#{player?.posRank}/{player?.posTotal} {player?.pos}</span></div><p className="meaning">NVI measures sustainable value relative to position, usage, and sample size.</p></Panel><div className="metricCards">{playerMetrics(player).map(m=><PlayerMetric key={m.label} {...m}/>)}</div></div><Panel><h3>49ers Position Board</h3><div className="playerGrid">{filtered.map(p=><button key={p.id} onClick={()=>setSel(p)} className={player?.id===p.id?'active':''}><span>{p.pos}</span><b>{p.name}</b><em>NVI {fmt(p.nvi,'nvi')} · #{p.posRank}/{p.posTotal}</em></button>)}</div></Panel></>}
function playerMetrics(p={stats:{}}){const s=p.stats||{}; const base=[['NVI Percentile',`${p.percentile||'—'}%`,'Position context','Compared only to players at the same position.'],['Sample Confidence',p.confidence||'—','Trust level','Protects against backups with tiny samples.'],['Usage',p.usage||'—','Role volume','Higher volume makes efficiency harder to sustain.']]; if(p.pos==='QB')return [...base,['EPA/Dropback',fmt(s.epa,'off_epa'),'Efficiency','Creates value each time he drops back.'],['CPOE',s.cpoe?`${s.cpoe.toFixed(1)}%`:'—','Accuracy over expectation','Shows throw accuracy beyond completion rate.'],['Pressure EPA',fmt(s.pressure,'off_epa'),'Pocket response','How performance holds up under disruption.']]; if(['WR','TE'].includes(p.pos))return [...base,['EPA/Target',fmt(s.epaTarget??s.epa,'off_epa'),'Target value','Value created when targeted.'],['Yards/Route',s.yprr?.toFixed?.(2)||'—','Efficiency','Receiving output independent of raw volume.'],['Target Share',s.share?`${(s.share*100).toFixed(1)}%`:'—','Usage','How central he is to the passing game.']]; if(p.pos==='RB')return [...base,['EPA/Rush',fmt(s.epa,'off_epa'),'Rush value','Value generated through carries.'],['Success Rate',s.success?`${(s.success*100).toFixed(1)}%`:'—','Schedule','Keeps the offense on schedule.'],['Explosive Rate',s.explosive?`${(s.explosive*100).toFixed(1)}%`:'—','Chunk plays','Creates hidden field-position value.']]; return [...base,['Pressure/Stops',s.pressure?`${(s.pressure*100).toFixed(1)}%`:s.stops?`${(s.stops*100).toFixed(1)}%`:'—','Disruption','Creates negative plays or limits efficiency.'],['Coverage/Success',s.coverage?fmt(s.coverage,'off_epa'):s.success?`${(s.success*100).toFixed(1)}%`:'—','Situational value','How stable the player is snap to snap.'],['Explosive Control',s.explosive?`${(s.explosive*100).toFixed(1)}%`:'—','Limiters','Suppresses big-play volatility.']];}
function PlayerMetric({label,value,sub,children}){return <div className="pmetric"><span>{label}</span><b>{value}</b><em>{sub}</em><p>{children}</p></div>}
function QBLab({qbs}){return <><SectionTitle eyebrow="QUARTERBACK COMMAND" title="NFL QB Matrix" sub="EPA and CPOE plotted for 32 quarterbacks."/><Panel><QBScatter qbs={qbs}/></Panel><Panel><h3>QB Ranking Board</h3><div className="rankList full">{[...qbs].sort((a,b)=>b.epa-a.epa).map((q,i)=><div key={q.name} className={q.team==='SF'?'sf':''}><b>#{i+1}</b><img src={q.logo}/><span>{q.name}<small>{q.team}</small></span><em>{fmt(q.epa,'off_epa')}</em></div>)}</div></Panel></>}
function QBScatter({qbs}){const w=720,h=420,p=56; const xs=q=>p+scaleValue(q.epa,-.10,.28)*(w-2*p)/100; const ys=q=>h-p-scaleValue(q.cpoe,-5,8)*(h-2*p)/100; return <div className="chartWrap"><svg className="scatterSvg" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="xMidYMid meet"><rect width={w} height={h} rx="24" fill="#07090d"/><line x1={w/2} x2={w/2} y1={p} y2={h-p} className="avgLine"/><line x1={p} x2={w-p} y1={h/2} y2={h/2} className="avgLine"/><text x={w/2} y={h-14} textAnchor="middle" className="axis">EPA / Dropback →</text><text x="18" y={h/2} transform={`rotate(-90 18 ${h/2})`} textAnchor="middle" className="axis">CPOE →</text>{qbs.map(q=><g key={q.name} transform={`translate(${xs(q)} ${ys(q)})`}><circle r={q.team==='SF'?18:11} className={q.team==='SF'?'sfHalo':'logoBack'}/><image href={q.logo} x={q.team==='SF'?-15:-9} y={q.team==='SF'?-15:-9} width={q.team==='SF'?30:18} height={q.team==='SF'?30:18}/><title>{q.name} · {q.team} · EPA ${fmt(q.epa,'off_epa')} · CPOE ${q.cpoe.toFixed(1)}%</title></g>)}</svg></div>}
function Intelligence({league,sf}){return <><SectionTitle eyebrow="WINNING FOOTBALL" title="Situational + Pressure + Coaching" sub="Context for how teams win critical downs."/><div className="grid three"><Panel><h3>Situational Center</h3><Situations sf={sf}/></Panel><Panel><h3>Pressure Map</h3><PressureMap sf={sf}/></Panel><Panel><h3>Coaching Tendencies</h3><Coaching sf={sf}/></Panel></div></>}
function Situations({sf}){const rows=[['3rd Down',sf.third_down,'third_down'],['Red Zone',sf.red_zone_epa,'red_zone_epa'],['Explosive',sf.explosive_rate,'explosive_rate'],['Success',sf.success_rate,'success_rate']]; return <div className="bars">{rows.map(([l,v,k])=><div key={l}><span>{l}</span><i><em style={{width:`${METRICS[k]?.unit==='%'?(num(v)||0)*100:scaleValue(num(v)||0,-.1,.2)}%`}}/></i><b>{fmt(v,k)}</b></div>)}</div>}
function PressureMap({sf}){const vals=[['Left Edge',68],['Interior',54],['Right Edge',72],['Blitz Pickup',61]]; return <div className="pressureGrid">{vals.map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b><i><em style={{width:`${v}%`}}/></i></div>)}</div>}
function Coaching({sf}){return <div className="stack"><Stat label="Neutral Pass Rate" value={fmt(sf.neutral_pass_rate,'neutral_pass_rate')} rank={sf.neutral_pass_rate_rank} total={32} meaning="Playcalling identity in balanced game states."/><Stat label="Pressure Creation" value={fmt(sf.pressure_rate,'pressure_rate')} rank={sf.pressure_rate_rank} total={32} meaning="Defensive disruption profile."/></div>}
function Personnel({players,league,sf}){const starters=players.filter(p=>['QB','RB','WR','TE','EDGE','LB','CB'].includes(p.pos)).slice(0,11); return <><SectionTitle eyebrow="PERSONNEL INTELLIGENCE" title="Formation + Role Context" sub="Usage and effectiveness should always be compared to league baselines."/><div className="grid two"><Panel><h3>Top Offensive Personnel</h3><Formation name="11 Personnel" use="62%" epa={sf.off_epa} rank="Top 10"/><Formation name="12 Personnel" use="18%" epa={sf.red_zone_epa} rank="Red-zone fit"/><Formation name="21 Personnel" use="11%" epa={sf.success_rate} rank="Play-action identity"/></Panel><Panel><h3>Starting 11 Board</h3><div className="field">{starters.map((p,i)=><div className={`node n${i}`} key={p.id}><img src={p.headshot}/><span>{p.pos}</span><small>{p.name.split(' ').at(-1)}</small></div>)}</div></Panel></div></>}
function Formation({name,use,epa,rank}){return <div className="formation"><b>{name}</b><span>Usage {use}</span><em>{rank}</em><p>Effectiveness: {fmt(epa,'off_epa')} · league context shown when personnel data is generated.</p></div>}
function Matchups({league}){const [sel,setSel]=useState(defaultSchedule[0]); const sf=league.find(t=>t.team==='SF')||{}; const opp=league.find(t=>t.team===sel.opponent)||{}; const edge=(num(sf.off_epa)||0)-(num(opp.def_epa_allowed)||0); return <><SectionTitle eyebrow="MATCHUP CENTER" title="2026 Game Intelligence" sub="Uses 2025 baselines until 2026 data is available."/><div className="matchLayout"><Panel><div className="gameList">{defaultSchedule.map(g=><button key={g.week} className={sel.week===g.week?'active':''} onClick={()=>setSel(g)}><img src={g.logo}/><span>Week {g.week}</span><b>49ers vs {g.opponent}</b><small>{g.opponentName}</small></button>)}</div></Panel><Panel><div className="versus"><img src={logo('SF')}/><b>49ers</b><span>VS</span><b>{sel.opponent}</b><img src={sel.logo}/></div><div className="matrix"><div><b>Category</b><b>SF</b><b>Edge</b><b>{sel.opponent}</b></div><div><span>Offense vs Defense</span><b>{fmt(sf.off_epa,'off_epa')}</b><b className={edge>0?'good':'bad'}>{edge>0?'SF':'OPP'}</b><b>{fmt(opp.def_epa_allowed,'def_epa_allowed')}</b></div><div><span>Explosive Profile</span><b>{fmt(sf.explosive_rate,'explosive_rate')}</b><b>{sf.explosive_rate_rank&&opp.explosive_rate_rank?sf.explosive_rate_rank<opp.explosive_rate_rank?'SF':'OPP':'—'}</b><b>{fmt(opp.explosive_rate,'explosive_rate')}</b></div><div><span>Pressure</span><b>{fmt(sf.pressure_rate,'pressure_rate')}</b><b>{sf.pressure_rate_rank&&opp.pressure_rate_rank?sf.pressure_rate_rank<opp.pressure_rate_rank?'SF':'OPP':'—'}</b><b>{fmt(opp.pressure_rate,'pressure_rate')}</b></div></div><div className="why"><b>What this means</b><p>{edge>0?'San Francisco projects to have a favorable efficiency matchup if early-down offense stays on schedule.':'The opponent profile creates pressure on San Francisco to win explosives and third down.'}</p></div></Panel></div></>}
function Creator({league,metric}){const ref=useRef(null); const exportPng=()=>{const svg=ref.current?.querySelector('svg'); if(!svg)return; const clone=svg.cloneNode(true); clone.querySelectorAll('image').forEach(img=>{const parent=img.parentNode; const text=document.createElementNS('http://www.w3.org/2000/svg','text'); text.setAttribute('x',img.getAttribute('x')); text.setAttribute('y',Number(img.getAttribute('y'))+18); text.setAttribute('fill','#fff'); text.setAttribute('font-size','10'); text.setAttribute('font-weight','900'); text.textContent=parent?.querySelector('title')?.textContent?.slice(0,3)||'NFL'; parent.replaceChild(text,img);}); const s=new XMLSerializer().serializeToString(clone); const img=new Image(); const blob=new Blob([s],{type:'image/svg+xml'}); const url=URL.createObjectURL(blob); img.onload=()=>{const canvas=document.createElement('canvas'); canvas.width=1200; canvas.height=800; const c=canvas.getContext('2d'); c.fillStyle='#050609'; c.fillRect(0,0,1200,800); c.fillStyle='#fff'; c.font='bold 34px Arial'; c.fillText('NINERVISION',48,56); c.fillStyle='#b3995d'; c.font='bold 18px Arial'; c.fillText('49ers Intelligence',48,84); c.drawImage(img,40,112,1120,620); c.fillStyle='#8d97a8'; c.font='16px Arial'; c.fillText('niner-vision.vercel.app · exported with active filters',48,760); const a=document.createElement('a'); a.download='ninervision-chart.png'; a.href=canvas.toDataURL('image/png'); a.click(); URL.revokeObjectURL(url);}; img.src=url;}; return <><SectionTitle eyebrow="CREATOR STUDIO" title="Export-Ready Visuals" sub="Branded share graphics without broken remote-logo exports."/><Panel><div className="exportHead"><div><b>NINERVISION</b><span>49ers Intelligence</span></div><button onClick={exportPng}><Download size={16}/> Export PNG</button></div><div ref={ref}><TeamTierChart rows={league}/></div></Panel><Panel><h3>Export Notes</h3><p className="meaning">Exports use embedded NinerVision branding and safe text fallbacks so remote team-logo CORS issues do not create broken images.</p></Panel></>}
function DataEngine({league,players,qbs}){return <Panel><h3>Data Confidence</h3><div className="grid three"><Stat label="Teams Loaded" value={league.length}/><Stat label="Players Loaded" value={players.length}/><Stat label="QBs Loaded" value={qbs.length}/></div></Panel>}

createRoot(document.getElementById('root')).render(<App/>);
