import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, BarChart3, Brain, CalendarDays, ChevronDown, Download, Eye, Gauge, Home, LineChart, Menu, Network, Search, Shield, TrendingUp, Users, X, Zap} from 'lucide-react';
import './styles.css';

const TEAMS=['ARI','ATL','BAL','BUF','CAR','CHI','CIN','CLE','DAL','DEN','DET','GB','HOU','IND','JAX','KC','LAC','LAR','LV','MIA','MIN','NE','NO','NYG','NYJ','PHI','PIT','SEA','SF','TB','TEN','WAS'];
const NAMES={ARI:'Cardinals',ATL:'Falcons',BAL:'Ravens',BUF:'Bills',CAR:'Panthers',CHI:'Bears',CIN:'Bengals',CLE:'Browns',DAL:'Cowboys',DEN:'Broncos',DET:'Lions',GB:'Packers',HOU:'Texans',IND:'Colts',JAX:'Jaguars',KC:'Chiefs',LAC:'Chargers',LAR:'Rams',LV:'Raiders',MIA:'Dolphins',MIN:'Vikings',NE:'Patriots',NO:'Saints',NYG:'Giants',NYJ:'Jets',PHI:'Eagles',PIT:'Steelers',SEA:'Seahawks',SF:'49ers',TB:'Buccaneers',TEN:'Titans',WAS:'Commanders'};
const logo=t=>`https://a.espncdn.com/i/teamlogos/nfl/500/${String(t==='WAS'?'wsh':t||'sf').toLowerCase()}.png`;
const headshot=id=>id?`https://a.espncdn.com/i/headshots/nfl/players/full/${id}.png`:'';
const PAGES=[['vision',Home,'Vision'],['landscape',Eye,'Landscape'],['charts',BarChart3,'Charts'],['players',Users,'Players'],['qb',Zap,'QB Lab'],['personnel',Network,'Personnel'],['situational',Activity,'Situations'],['matchups',CalendarDays,'Matchups'],['creator',Download,'Creator'],['data',Shield,'Data']];
const MOBILE_PRIMARY=['vision','landscape','charts','players','more'];
const METRICS={
 nvi:{label:'NVI Score',short:'NVI',better:'higher',unit:'',why:'A sustainability lens: efficiency, explosiveness, defensive stability, pressure, and situational football.'},
 off_epa:{label:'Offensive EPA / Play',short:'Off EPA',better:'higher',unit:'',why:'Value created by the offense on a per-play basis.'},
 def_epa_allowed:{label:'Defensive EPA Allowed',short:'Def EPA',better:'lower',unit:'',why:'Value allowed by the defense. Lower is better.'},
 success_rate:{label:'Success Rate',short:'Success',better:'higher',unit:'%',why:'How often the unit stays on schedule.'},
 explosive_rate:{label:'Explosive Rate',short:'Explosive',better:'higher',unit:'%',why:'Chunk-play creation rate.'},
 points_per_drive:{label:'Points / Drive',short:'Pts/Drive',better:'higher',unit:'',why:'How efficiently drives become points.'},
 red_zone_epa:{label:'Red Zone EPA',short:'Red Zone',better:'higher',unit:'',why:'Efficiency in scoring territory.'},
 third_down:{label:'3rd Down Rate',short:'3rd Down',better:'higher',unit:'%',why:'Drive-extension ability.'},
 neutral_pass_rate:{label:'Neutral Pass Rate',short:'Pass Rate',better:'higher',unit:'%',why:'Passing tendency in balanced game states.'},
 pressure_rate:{label:'Pressure Rate',short:'Pressure',better:'higher',unit:'%',why:'How often the defense disrupts the QB.'},
 pressure_allowed:{label:'Pressure Allowed',short:'Press Allowed',better:'lower',unit:'%',why:'How often the offense allows disruption.'}
};
const CHART_METRICS=Object.keys(METRICS);
const defaultSchedule=['LAR','SEA','ARI','KC','PHI','DAL','MIA','MIN','DEN','LAC','LV','ATL'].map((opponent,i)=>({week:i+1,opponent,opponentName:NAMES[opponent],logo:logo(opponent),note:i===0?'International opener':'2026 preview'}));
const fallbackPlayers=[
 {name:'Brock Purdy',pos:'QB',team:'SF',espn:'4361741',usage:610,stats:{epa:.194,cpoe:3.8,success:.51,adot:8.2,deep:.094,pressure:.13,third:.49,red:.28}},
 {name:'Mac Jones',pos:'QB',team:'SF',espn:'4241464',usage:128,stats:{epa:.036,cpoe:1.1,success:.43,adot:7.2,deep:.071,pressure:.18,third:.37,red:.04}},
 {name:'Christian McCaffrey',pos:'RB',team:'SF',espn:'3117251',usage:295,stats:{epa:.062,success:.49,explosive:.105,touches:312,targets:82,redShare:.33,yac:4.1}},
 {name:'George Kittle',pos:'TE',team:'SF',espn:'3040151',usage:92,stats:{targets:88,share:.19,catch:.76,yprr:2.21,epaTarget:.39,yac:6.1,explosive:.18}},
 {name:'Jauan Jennings',pos:'WR',team:'SF',espn:'4040655',usage:102,stats:{targets:94,share:.21,catch:.61,yprr:1.82,epaTarget:.09,yac:3.7,explosive:.13}},
 {name:'Ricky Pearsall',pos:'WR',team:'SF',espn:'4430878',usage:73,stats:{targets:70,share:.16,catch:.66,yprr:1.74,epaTarget:.16,yac:4.5,explosive:.16}},
 {name:'Fred Warner',pos:'LB',team:'SF',espn:'3138826',usage:950,stats:{stops:.103,coverage:.18,pressure:.11,success:.71,explosive:.05}},
 {name:'Nick Bosa',pos:'EDGE',team:'SF',espn:'4040605',usage:812,stats:{pressure:.168,sackConv:.14,stops:.085,success:.66,explosive:.04}},
 {name:'Deommodore Lenoir',pos:'CB',team:'SF',espn:'4361539',usage:790,stats:{coverage:.12,success:.62,explosive:.07,stops:.052,pressure:.03}}
];

const num=v=>Number.isFinite(Number(v))?Number(v):null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function fmt(v,key){const n=num(v); if(n===null) return '—'; if(METRICS[key]?.unit==='%') return `${(n*100).toFixed(1)}%`; if(key==='nvi') return Math.round(n); if(Math.abs(n)<1) return `${n>0?'+':''}${n.toFixed(3)}`; return n.toFixed(1);}
function pct(v){const n=num(v); return n===null?'—':`${(n*100).toFixed(1)}%`;}
function rankRows(rows,key){const high=METRICS[key]?.better!=='lower'; return [...rows].filter(r=>num(r[key])!==null).sort((a,b)=>high?num(b[key])-num(a[key]):num(a[key])-num(b[key])).map((r,i)=>({...r,rank:i+1}));}
function percentile(rank,total){return rank?Math.round((1-(rank-1)/Math.max(total-1,1))*100):null;}
function avg(rows,key){const xs=rows.map(r=>num(r[key])).filter(v=>v!==null); return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;}
function tier(r){const n=num(r.nvi)||75, off=num(r.off_epa)||0, def=num(r.def_epa_allowed)||0; if(n>=90&&off>0.02&&def<0.04)return 'Elite'; if(n>=84)return 'Sustainable Contender'; if(off>0.05)return 'Offense-Carried'; if(def<0)return 'Defense-Carried'; if(n<72)return 'Rebuild / Volatile'; return 'Volatile';}
function adaptLeague(raw){let rows=Array.isArray(raw)?raw:(raw?.teams||raw?.league||raw?.data||[]); if(!rows.length) rows=TEAMS.map((t,i)=>({team:t})); rows=rows.map((r,i)=>{const t=r.team||r.recent_team||r.abbr||TEAMS[i%32]; const off=num(r.off_epa??r.epa_off??r.offensive_epa)??((16-i)/600); const def=num(r.def_epa_allowed??r.def_epa??r.epa_allowed)??((i-16)/700); const success=num(r.success_rate??r.success)??(.39+(i%12)/100); const expl=num(r.explosive_rate??r.explosive)??(.055+(i%10)/1000); const ppd=num(r.points_per_drive??r.ppd)??(1.45+(i%12)/16); const rz=num(r.red_zone_epa??r.rz_epa)??((10-i)/900); const third=num(r.third_down??r.third_down_rate)??(.35+(i%10)/100); const npr=num(r.neutral_pass_rate??r.pass_rate)??(.47+(i%13)/100); const pr=num(r.pressure_rate)??(.28+(i%9)/100); const pa=num(r.pressure_allowed)??(.26+(i%9)/100); const nvi=num(r.nvi??r.nv_index??r.nvi_score)??clamp(55+(off*460)-(def*360)+(success*30)+(expl*80)+(ppd*7)+(rz*170)+(third*15)+(pr*13)-(pa*13),48,98); return {...r,team:t,name:r.name||NAMES[t]||t,logo:r.logo||logo(t),off_epa:off,def_epa_allowed:def,success_rate:success,explosive_rate:expl,points_per_drive:ppd,red_zone_epa:rz,third_down:third,neutral_pass_rate:npr,pressure_rate:pr,pressure_allowed:pa,nvi}; }); CHART_METRICS.forEach(k=>rankRows(rows,k).forEach(rr=>{const x=rows.find(r=>r.team===rr.team); if(x)x[`${k}_rank`]=rr.rank;})); return rows.map(r=>({...r,tier:tier(r)}));}
function adaptPlayers(raw){let arr=Array.isArray(raw)?raw:(raw?.players||raw?.data||[]); if(!arr.length) arr=fallbackPlayers; const sf=arr.map((p,i)=>{const name=p.name||p.player_name||p.full_name||fallbackPlayers[i%fallbackPlayers.length].name; const pos=(p.pos||p.position||fallbackPlayers[i%fallbackPlayers.length].pos||'UNK').toUpperCase(); const team=p.team||p.recent_team||'SF'; const stats=p.stats||{}; const usage=num(p.usage??p.routes??p.targets??p.carries??p.attempts??p.snaps)??num(stats.targets??stats.touches??stats.carries)??(pos==='QB'?num(stats.attempts)||180:pos==='RB'?160:pos==='WR'||pos==='TE'?70:500); return {id:p.id||p.player_id||name, name, pos, team, usage, headshot:p.headshot||p.headshot_url||p.espn_headshot||headshot(p.espn), stats:{...stats, epa:num(stats.epa??p.epa??p.rush_epa??p.rec_epa)??num(p.epa_per_play), cpoe:num(stats.cpoe??p.cpoe), success:num(stats.success??stats.success_rate??p.success_rate), explosive:num(stats.explosive??stats.explosive_rate??p.explosive_rate)}}}).filter(p=>p.team==='SF'||!p.team); return computePlayerNvi(sf.length?sf:fallbackPlayers);}
function computePlayerNvi(players){const by={}; players.forEach(p=>{(by[p.pos] ||= []).push(p)}); return players.map(p=>{const group=by[p.pos]||[p]; const q=s=>num(p.stats?.[s]); const base = p.pos==='QB' ? (q('epa')||0)*250 + (q('cpoe')||0)*3 + (q('success')||.42)*40 - (q('pressure')||.18)*25 + 45 : ['WR','TE'].includes(p.pos) ? (q('epaTarget')||q('epa')||0)*90 + (q('catch')||.62)*28 + (q('yprr')||1.2)*10 + (q('share')||.10)*55 + (q('explosive')||.10)*65 + 35 : p.pos==='RB' ? (q('epa')||0)*120 + (q('success')||.42)*34 + (q('explosive')||.09)*75 + (q('redShare')||.12)*35 + 42 : ['EDGE','DL'].includes(p.pos) ? (q('pressure')||.08)*210 + (q('stops')||.06)*120 + (q('success')||.55)*30 + 35 : ['LB','CB','DB','S'].includes(p.pos) ? (q('coverage')||.05)*90 + (q('stops')||.05)*110 + (q('success')||.55)*35 - (q('explosive')||.08)*120 + 38 : 62;
 const threshold=p.pos==='QB'?150:p.pos==='RB'?100:['WR','TE'].includes(p.pos)?45:350; const confidence=p.usage>=threshold*1.5?'High':p.usage>=threshold?'Qualified':p.usage>=threshold*.45?'Limited':'Insufficient'; const volumeFactor=confidence==='High'?1:confidence==='Qualified'?.95:confidence==='Limited'?.82:.68; return {...p, rawNvi:clamp(base,35,99), nvi:clamp(base*volumeFactor + 8*(1-volumeFactor),35,97), confidence}; }).map((p,_,all)=>{const g=all.filter(x=>x.pos===p.pos).sort((a,b)=>b.nvi-a.nvi); const rank=g.findIndex(x=>x.id===p.id)+1; return {...p,posRank:rank,posTotal:g.length,percentile:percentile(rank,g.length),tier:p.nvi>=88?'Elite':p.nvi>=78?'Impact':p.nvi>=68?'Starter':p.nvi>=58?'Rotation':'Depth'};});}
function adaptQbs(raw,players){const arr=Array.isArray(raw)?raw:(raw?.qbs||raw?.data||[]); if(arr.length){return arr.map((q,i)=>({name:q.name||q.player_name||q.passer_player_name,team:q.team||q.recent_team||'SF',logo:q.logo||logo(q.team||q.recent_team||'SF'),epa:num(q.epa??q.epa_per_dropback)??0,cpoe:num(q.cpoe)??0,success:num(q.success??q.success_rate)??.42,pressure_epa:num(q.pressure_epa)??-0.05,rank:i+1})).filter(q=>q.name);} return players.filter(p=>p.pos==='QB').map((p,i)=>({name:p.name,team:'SF',logo:logo('SF'),epa:num(p.stats.epa)||.05,cpoe:num(p.stats.cpoe)||0,success:num(p.stats.success)||.43,pressure_epa:num(p.stats.pressure_epa)||-.05,rank:i+1}));}
function adaptSchedule(raw){const arr=Array.isArray(raw)?raw:(raw?.schedule||raw?.games||raw?.data||[]); if(!arr.length)return defaultSchedule; return arr.map((g,i)=>{const opp=g.opponent||(g.home_team==='SF'?g.away_team:g.away_team==='SF'?g.home_team:null)||defaultSchedule[i%defaultSchedule.length].opponent; return {week:g.week||i+1,opponent:opp,opponentName:g.opponentName||NAMES[opp]||opp,logo:g.logo||logo(opp),note:g.note||g.game_type||'Projection'};});}
async function fetchJson(paths){for(const p of paths){try{const r=await fetch(p,{cache:'no-store'}); if(r.ok)return {json:await r.json(),path:p};}catch{}} return {json:null,path:'demo fallback'};}
const AppCtx=React.createContext(null); const useApp=()=>React.useContext(AppCtx);
function App(){const [page,setPage]=useState('vision'); const [filters,setFilters]=useState({season:'2025',range:'regular',week:'all'}); const [data,setData]=useState({league:adaptLeague(null),players:computePlayerNvi(fallbackPlayers),qbs:[],schedule:defaultSchedule,source:'loading'}); const [loading,setLoading]=useState(false); useEffect(()=>{let live=true; (async()=>{setLoading(true); const season=filters.season, suffix=filters.week!=='all'?`/weeks/week_${String(filters.week).padStart(2,'0')}`:filters.range==='plus_playoffs'?'/regular_plus_playoffs':'/regular_season'; const [lg,pl,qb,sc]=await Promise.all([fetchJson([`/data/${season}${suffix}.json`,`/data/league_${season}.json`,`/data/league_${season}_demo.json`]),fetchJson([`/data/players_${season}.json`,`/data/players_${season}_demo.json`]),fetchJson([`/data/qbs_${season}.json`,`/data/qbs_${season}_demo.json`]),fetchJson([`/data/schedule_2026.json`,`/data/schedule_2026_demo.json`])]); const players=adaptPlayers(pl.json); if(live){setData({league:adaptLeague(lg.json),players,qbs:adaptQbs(qb.json,players),schedule:adaptSchedule(sc.json),source:lg.path});setLoading(false)}})(); return()=>{live=false}},[filters]); const sf=useMemo(()=>data.league.find(t=>t.team==='SF')||data.league[0]||{},[data.league]); const value={page,setPage,filters,setFilters,data,sf,loading}; return <AppCtx.Provider value={value}><Shell/></AppCtx.Provider>}
function Shell(){const {page,setPage,filters,setFilters,loading,data}=useApp(); const [more,setMore]=useState(false); const comp={vision:<Vision/>,landscape:<Landscape/>,charts:<Charts/>,players:<Players/>,qb:<QBLab/>,personnel:<Personnel/>,situational:<Situational/>,matchups:<Matchups/>,creator:<Creator/>,data:<DataEngine/>}[page]||<Vision/>; const nav=(id)=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMore(false);}}>{React.createElement(PAGES.find(p=>p[0]===id)?.[1]||Menu,{size:18})}<span>{PAGES.find(p=>p[0]===id)?.[2]}</span></button>; return <><header className="topbar"><button className="brandBtn" onClick={()=>setPage('vision')}><b>NINER<span>VISION</span></b><small>49ers Intelligence</small></button><div className="filters"><select value={filters.season} onChange={e=>setFilters({...filters,season:e.target.value})}><option>2025</option><option>2024</option></select><select value={filters.range} onChange={e=>setFilters({...filters,range:e.target.value})}><option value="regular">Full Season</option><option value="plus_playoffs">Full Season + Playoffs</option></select><select value={filters.week} onChange={e=>setFilters({...filters,week:e.target.value})}><option value="all">All Weeks</option>{Array.from({length:18},(_,i)=><option key={i+1} value={i+1}>Week {i+1}</option>)}</select></div><span className="source">{data.league.length} teams · {filters.week==='all'?'season':`week ${filters.week}`}</span></header><aside className="sidebar">{PAGES.map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={18}/><span>{label}</span></button>)}</aside><main className="page">{comp}</main><nav className="bottomnav">{MOBILE_PRIMARY.map(id=>id==='more'?<button key="more" className={more?'active':''} onClick={()=>setMore(!more)}><Menu size={18}/><span>More</span></button>:nav(id))}</nav>{more&&<div className="moreSheet"><button className="close" onClick={()=>setMore(false)}><X size={18}/> Close</button>{PAGES.filter(p=>!['vision','landscape','charts','players'].includes(p[0])).map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMore(false)}}><Icon size={18}/><span>{label}</span></button>)}</div>}{loading&&<div className="loading"><span/>Loading selected data</div>}</>}
function Title({k,h,p}){return <div className="title"><span>{k}</span><h1>{h}</h1>{p&&<p>{p}</p>}</div>}
function Panel({title,sub,children,action}){return <section className="panel"><div className="panelHead"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>{children}</section>}
function Vision(){const {sf,setPage}=useApp();return <><section className="hero panel"><div><span className="eyebrow">NinerVision System</span><h1>NINER<span>VISION</span></h1><p>Football intelligence, not stat noise. Every number needs context, rank, and meaning.</p><div className="actions"><button onClick={()=>setPage('landscape')}>Open NFL Landscape</button><button className="ghost" onClick={()=>setPage('matchups')}>View Matchups</button></div></div><NviSummary team={sf}/></section><section className="grid two"><Panel title="Featured NFL Landscape" sub="One clean view of offensive value vs defensive resistance."><TeamTierChart rows={useApp().data.league} compact/></Panel><Panel title="Why NVI Matters" sub="The score only matters when the components are visible."><NviBreakdown team={sf}/></Panel></section><section className="quickGrid">{[['landscape','NFL Landscape','Team tiers + league context'],['players','Player Profiles','Position-context cards'],['qb','QB Lab','EPA, CPOE, pressure'],['personnel','Personnel Lab','11/12/21 groups'],['situational','Situational Center','Red zone, 3rd down, pressure'],['creator','Creator Studio','Export branded graphics']].map(([id,a,b])=><button key={id} className="quick" onClick={()=>useApp().setPage(id)}><b>{a}</b><small>{b}</small></button>)}</section></>}
function NviSummary({team}){const rank=team.nvi_rank||rankRows(useApp().data.league,'nvi').find(r=>r.team===team.team)?.rank||6;return <article className="nviCard"><div className="ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="50"/><circle className="meter" cx="60" cy="60" r="50" strokeDasharray={`${(team.nvi||85)/100*314} 314`}/></svg><strong>{Math.round(team.nvi||85)}</strong></div><div><span className="pill gold">{team.tier||'Contender'}</span><h2>{team.tier||'Balanced Contender'}</h2><p>NVI blends efficiency, explosiveness, defensive stability, pressure, and situational football into one sustainability lens.</p><div className="split"><b>Rank #{rank}/32</b><b>{percentile(rank,32)}th pct</b></div></div></article>}
function NviBreakdown({team}){const rows=[['Offense',team.off_epa_rank],['Defense',team.def_epa_allowed_rank],['Explosive',team.explosive_rate_rank],['Sustainability',team.success_rate_rank],['Pressure',team.pressure_rate_rank],['Situational',team.third_down_rank]];return <div className="breakdown">{rows.map(([k,r])=>{const p=percentile(r||16,32);return <div key={k}><span>{k}</span><b>{p}</b><i><em style={{width:`${p}%`}}/></i></div>})}<p className="note">Designed to reward repeatable value, not one-week volatility.</p></div>}
function Landscape(){const {data}=useApp();return <><Title k="Landscape" h="NFL Team Ecosystem" p="League-wide context: offense, defense, tier lanes, and where the 49ers sit."/><Panel title="Team Tiers 3.0" sub="Diagonal bands separate elite contenders, offense-carried teams, defense-carried teams, and volatile rebuild profiles."><TeamTierChart rows={data.league}/></Panel><section className="grid two"><Ranking metric="nvi"/><Ranking metric="off_epa"/></section></>}
function TeamTierChart({rows,compact=false}){const w=920,h=560, m={l:72,r:48,t:58,b:64}; const xs=rows.map(r=>num(r.off_epa)||0), ys=rows.map(r=>num(r.def_epa_allowed)||0); const minX=Math.min(-.22,...xs), maxX=Math.max(.17,...xs), minY=Math.min(-.16,...ys), maxY=Math.max(.18,...ys); const sx=x=>m.l+(x-minX)/(maxX-minX)*(w-m.l-m.r); const sy=y=>m.t+(y-minY)/(maxY-minY)*(h-m.t-m.b); const leagueX=avg(rows,'off_epa'), leagueY=avg(rows,'def_epa_allowed'); const bands=[-.22,-.12,-.02,.08,.18]; return <div className="chartScroll"><svg className={`tierChart ${compact?'compact':''}`} viewBox={`0 0 ${w} ${h}`}><defs><linearGradient id="tierBg" x1="0" x2="1" y1="1" y2="0"><stop offset="0" stopColor="#3b0d13" stopOpacity=".55"/><stop offset=".48" stopColor="#0b1119" stopOpacity=".68"/><stop offset="1" stopColor="#8b6c25" stopOpacity=".58"/></linearGradient><linearGradient id="bandGold" x1="0" x2="1"><stop stopColor="#ffffff" stopOpacity=".05"/><stop offset="1" stopColor="#f0d58c" stopOpacity=".30"/></linearGradient></defs><rect x="14" y="14" width={w-28} height={h-28} rx="30" className="chartShell"/><rect x={m.l} y={m.t} width={w-m.l-m.r} height={h-m.t-m.b} rx="22" fill="url(#tierBg)"/>{bands.map((b,i)=><line key={b} x1={sx(minX)} y1={sy(minX-b)} x2={sx(maxX)} y2={sy(maxX-b)} className={`tierLine b${i}`}/>) }<line x1={sx(leagueX)} x2={sx(leagueX)} y1={m.t} y2={h-m.b} className="avgLine"/><line x1={m.l} x2={w-m.r} y1={sy(leagueY)} y2={sy(leagueY)} className="avgLine"/><text x={m.l+16} y={m.t+34} className="zoneText">DEFENSE-CARRIED</text><text x={w-300} y={m.t+34} className="zoneText gold">ELITE CONTENDER</text><text x={m.l+16} y={h-m.b-26} className="zoneText muted">REBUILD / VOLATILE</text><text x={w-310} y={h-m.b-26} className="zoneText">OFFENSE-CARRIED</text><text x="26" y={h/2} className="axis vertical">Better defense ↑</text><text x={w/2-80} y={h-24} className="axis">Offensive EPA/play →</text><text x="34" y={h-28} className="watermark">NINERVISION · 49ERS INTELLIGENCE</text>{rows.map(r=>{const x=sx(num(r.off_epa)||0), y=sy(num(r.def_epa_allowed)||0), is=r.team==='SF'; return <g key={r.team} className="teamLogo"><circle cx={x} cy={y} r={is?24:17} className={is?'sfHalo':'teamBubble'}/><image href={r.logo||logo(r.team)} x={x-(is?18:13)} y={y-(is?18:13)} width={is?36:26} height={is?36:26}/><title>{r.name||r.team} · {r.tier} · Off EPA ${fmt(r.off_epa,'off_epa')} · Def EPA ${fmt(r.def_epa_allowed,'def_epa_allowed')}</title></g>})}</svg></div>}
function Ranking({metric}){const {data}=useApp();const rows=rankRows(data.league,metric);return <Panel title={METRICS[metric].label} sub={METRICS[metric].why}><div className="rankList">{rows.slice(0,12).map(r=><div key={r.team} className={r.team==='SF'?'sf':''}><span>#{r.rank}</span><img src={r.logo}/><b>{r.name}</b><em>{fmt(r[metric],metric)}</em></div>)}</div></Panel>}
function Charts(){const [metric,setMetric]=useState('off_epa');return <><Title k="Charts" h="Advanced Visualization Library" p="Each chart has one home. Use the selector to reveal more without cluttering the page."/><Panel title="Chart Selector" action={<select value={metric} onChange={e=>setMetric(e.target.value)}>{CHART_METRICS.map(k=><option key={k} value={k}>{METRICS[k].label}</option>)}</select>}><Ranking metric={metric}/></Panel></>}
function Players(){const {data}=useApp(); const [id,setId]=useState(data.players[0]?.id||''); useEffect(()=>{if(data.players.length&&!data.players.find(p=>p.id===id))setId(data.players[0].id)},[data.players]); const player=data.players.find(p=>p.id===id)||data.players[0]; const positions=[...new Set(data.players.map(p=>p.pos))]; return <><Title k="Player Intelligence" h="49ers Player Profiles" p="Position-context cards with rank, percentile, confidence, and football-language meaning."/><div className="toolbar"><select value={id} onChange={e=>setId(e.target.value)}>{data.players.map(p=><option key={p.id} value={p.id}>{p.name} · {p.pos}</option>)}</select><span className="pill">Position-relative NVI</span>{positions.map(pos=><span key={pos} className="pill">{pos}</span>)}</div>{player&&<PlayerProfile player={player}/>}</>}
function metricCards(p){const s=p.stats||{}; if(p.pos==='QB')return [['EPA / Dropback',fmt(s.epa,'off_epa'),`${p.posRank} of ${p.posTotal} ${p.pos}s`,'Creates scoring value per QB dropback.'],['CPOE',s.cpoe!=null?`${Number(s.cpoe).toFixed(1)}%`:'—','Accuracy context','Completion rate over expected.'],['Success Rate',pct(s.success),'Schedule efficiency','Keeps the offense ahead of the chains.'],['ADOT',s.adot?.toFixed?.(1)||'—','Aggression profile','Average target depth.'],['Deep Ball Rate',pct(s.deep),'Explosive intent','Attempts 20+ yards downfield.'],['Pressure Rate',pct(s.pressure),'Pocket context','Dropbacks pressured or sacked.']]; if(['WR','TE'].includes(p.pos))return [['Targets',s.targets||'—',`${pct(s.share)} target share`,'Role and volume in the passing game.'],['Catch Rate',pct(s.catch),'Reliability','How often targets become completions.'],['Yards / Route',s.yprr?.toFixed?.(2)||'—',`${p.pos} efficiency`,'Production independent of raw volume.'],['EPA / Target',fmt(s.epaTarget||s.epa,'off_epa'),'Value per look','Expected value whenever targeted.'],['YAC / Rec',s.yac?.toFixed?.(1)||'—','After-catch impact','Extra value after the catch.'],['Explosive Rate',pct(s.explosive),'Chunk plays','Ability to create explosive gains.']]; if(p.pos==='RB')return [['Touches',s.touches||p.usage,'Usage','Workload and offensive role.'],['EPA / Rush',fmt(s.epa,'off_epa'),'Rushing value','Expected value per rush.'],['Success Rate',pct(s.success),'Down-to-down reliability','Keeps offense on schedule.'],['Explosive Run',pct(s.explosive),'Home-run threat','Chunk-play rushing rate.'],['Targets',s.targets||'—','Receiving role','Passing-game usage.'],['Red Zone Share',pct(s.redShare),'Scoring role','Touch share near the goal line.']]; return [['NVI',Math.round(p.nvi),`${p.percentile}th percentile`,'Position-relative football value.'],['Success',pct(s.success),'Reliability','Positive assignment/outcome proxy.'],['Pressure / Coverage',pct(s.pressure||s.coverage),'Impact','Disruption or coverage value proxy.'],['Stops',pct(s.stops),'Run support','Drive-ending involvement.'],['Explosive Allowed',pct(s.explosive),'Limiting damage','Lower is better for defenders.'],['Confidence',p.confidence,'Sample check','How trustworthy this sample is.']];}
function PlayerProfile({player}){return <section className="playerProfile"><article className="identity panel"><div className="playerPhoto">{player.headshot?<img src={player.headshot}/>:<b>{player.name[0]}</b>}</div><span className="pill gold">{player.pos}</span><h2>{player.name}</h2><p>San Francisco 49ers</p><div className="playerScore"><b>{Math.round(player.nvi)}</b><span>NVI · #{player.posRank} {player.pos} · {player.percentile}th pct</span></div><div className="split"><b>{player.tier}</b><b>{player.confidence}</b></div></article><div className="cards">{metricCards(player).map(([k,v,c,why])=><article className="statCard" key={k}><span>{k}</span><b>{v}</b><small>{c}</small><p>{why}</p></article>)}</div></section>}
function QBLab(){const {data}=useApp();return <><Title k="QB Lab" h="Quarterback Intelligence System" p="EPA, CPOE, pressure, and role context for NFL quarterbacks."/><Panel title="QB Efficiency Matrix" sub="Names and team logos placed on a mobile-safe scatter plot."><QbScatter rows={data.qbs}/></Panel></>}
function QbScatter({rows}){const w=900,h=520; const xs=rows.map(q=>num(q.epa)||0), ys=rows.map(q=>num(q.cpoe)||0); const minX=Math.min(-.18,...xs),maxX=Math.max(.28,...xs),minY=Math.min(-6,...ys),maxY=Math.max(7,...ys); const sx=x=>75+(x-minX)/(maxX-minX)*(w-140), sy=y=>h-70-(y-minY)/(maxY-minY)*(h-130); return <div className="chartScroll"><svg className="scatter" viewBox={`0 0 ${w} ${h}`}><rect x="12" y="12" width={w-24} height={h-24} rx="28"/><line x1="75" x2={w-60} y1={sy(0)} y2={sy(0)}/><line x1={sx(0)} x2={sx(0)} y1="55" y2={h-70}/><text x="26" y="42" className="chartTitle">EPA / Dropback vs CPOE</text>{rows.map((q,i)=>{const x=sx(num(q.epa)||0),y=sy(num(q.cpoe)||0),is=q.team==='SF'||/purdy/i.test(q.name);return <g key={q.name+i}><circle cx={x} cy={y} r={is?18:12} className={is?'sfHalo':'teamBubble'}/><image href={q.logo||logo(q.team)} x={x-(is?14:9)} y={y-(is?14:9)} width={is?28:18} height={is?28:18}/><text x={x+15} y={y-9} className={is?'sfText':'tiny'}>{String(q.name).split(' ').slice(-1)[0]}</text></g>})}<text x={w/2-70} y={h-24} className="axis">EPA →</text><text x="28" y={h-28} className="watermark">NINERVISION QB LAB</text></svg></div>}
function Personnel(){const {data}=useApp();return <><Title k="Personnel" h="Formation Intelligence" p="Top personnel groups, usage, league rank, and player role context."/><section className="grid two"><Panel title="Offensive Personnel" sub="Top groups by usage with effectiveness context."><PersonnelCards groups={[[ '11 Personnel','62%','+0.104','#6 NFL','Best explosive profile'],['21 Personnel','18%','+0.082','#4 NFL','Play-action stress'],['12 Personnel','11%','+0.061','#9 NFL','Red-zone utility']]}/></Panel><Panel title="Defensive Personnel" sub="Base, nickel, dime, and pressure-package identity."><PersonnelCards groups={[[ 'Nickel','71%','-0.026','#7 NFL','Primary coverage shell'],['Base Front','16%','-0.012','#12 NFL','Run-fit package'],['Dime','9%','-0.018','#10 NFL','Pass-down pressure']]}/></Panel></section><Panel title="Starting 11 Concept" sub="Demo layout now restricted to realistic offensive roles; next step is true depth-chart data."><FormationBoard players={data.players}/></Panel></>}
function PersonnelCards({groups}){return <div className="stack">{groups.map(g=><article className="miniPanel" key={g[0]}><b>{g[0]}</b><span>{g[4]}</span><div className="split"><em>Usage {g[1]}</em><em>EPA {g[2]}</em><em>{g[3]}</em></div></article>)}</div>}
function FormationBoard({players}){const roles=['QB','RB','WR','WR','WR','TE','LT','LG','C','RG','RT']; const pool=roles.map((r,i)=>players.find(p=>p.pos===r)||players.find(p=>r==='WR'&&p.pos==='TE')||players[i%players.length]); return <div className="field">{pool.map((p,i)=><div key={i} className={`node n${i}`}><span>{roles[i]}</span>{p?.headshot?<img src={p.headshot}/>:<b>{p?.name?.[0]||'?'}</b>}<small>{p?.name?.split(' ').slice(-1)[0]||'TBD'}</small></div>)}</div>}
function Situational(){return <><Title k="Situational Center" h="Winning Down Intelligence" p="Pressure, red zone, 3rd down, and coaching tendency context."/><section className="grid three"><SituationCard title="Pressure Map" value="Edge + Interior" desc="Pressure creation and vulnerability lanes."/><SituationCard title="3rd Down" value="Money Downs" desc="Conversion and pressure response."/><SituationCard title="Red Zone" value="Finish Rate" desc="Condensed-field scoring value."/></section><section className="grid two"><Panel title="Coaching Tendency Engine"><TendencyBars/></Panel><Panel title="Pressure Intelligence"><PressureMap/></Panel></section></>}
function SituationCard({title,value,desc}){return <article className="panel situation"><span className="pill gold">{title}</span><b>{value}</b><p>{desc}</p></article>}
function TendencyBars(){const rows=[['Motion / Shift Usage',84],['Play-Action Identity',79],['Early-Down Aggression',67],['Personnel Multiplicity',73],['4th-Down Aggression',54]];return <div className="bars">{rows.map(([k,v])=><div key={k}><span>{k}</span><i><em style={{width:`${v}%`}}/></i><b>{v}th pct</b></div>)}</div>}
function PressureMap(){return <svg className="pressure" viewBox="0 0 720 320"><rect x="10" y="10" width="700" height="300" rx="24"/><text x="24" y="40" className="chartTitle">Pressure Lanes</text>{[['LT',90,.45],['LG',210,.25],['C',330,.30],['RG',450,.22],['RT',570,.52]].map(([k,x,p])=><g key={k}><circle cx={x} cy="170" r={38+p*34} fill="rgba(170,0,0,.18)" stroke="rgba(242,213,139,.35)"/><text x={x-12} y="175" className="label">{k}</text></g>)}<path d="M90 250 C210 215 455 215 570 250" fill="none" stroke="rgba(242,213,139,.45)" strokeWidth="3" strokeDasharray="7 9"/><text x="24" y="292" className="watermark">NINERVISION PRESSURE MAP</text></svg>}
function Matchups(){const {data,sf}=useApp();const [sel,setSel]=useState(0); const game=data.schedule[sel]||defaultSchedule[0]; const opp=data.league.find(t=>t.team===game.opponent)||{};return <><Title k="Matchups" h="Game Intelligence Center" p="Clickable games open opponent reports with edge scoring and context."/><section className="matchLayout"><div className="gameList">{data.schedule.map((g,i)=><button key={i} className={i===sel?'active':''} onClick={()=>setSel(i)}><img src={g.logo}/><span>Week {g.week}</span><b>49ers vs {g.opponentName}</b><small>{g.note}</small></button>)}</div><Panel title={`49ers vs ${game.opponentName}`} sub={game.note}><div className="versus"><img src={logo('SF')}/><b>49ers</b><strong>VS</strong><b>{game.opponentName}</b><img src={game.logo}/></div><MatchMatrix sfTeam={sf} opp={opp}/><div className="why"><b>Why this matchup matters</b><p>San Francisco’s biggest edge is <b>{sf.third_down_rank<=10?'situational offense':'offensive efficiency'}</b>. The main watch point is whether pressure and red-zone variance swing the game.</p></div></Panel></section></>}
function MatchMatrix({sfTeam,opp}){const rows=[['Offense',sfTeam.off_epa,opp.def_epa_allowed,'off_epa'],['Explosive',sfTeam.explosive_rate,opp.explosive_rate,'explosive_rate'],['Pressure',sfTeam.pressure_rate,opp.pressure_allowed,'pressure_rate'],['Red Zone',sfTeam.red_zone_epa,opp.red_zone_epa,'red_zone_epa'],['3rd Down',sfTeam.third_down,opp.third_down,'third_down']];return <div className="matrix"><div><b>Category</b><b>SF</b><b>Edge</b><b>Opponent</b></div>{rows.map(([l,a,b,k])=>{const e=(num(a)||0)-(num(b)||0);return <div key={l}><span>{l}</span><b>{fmt(a,k)}</b><em className={e>=0?'good':'bad'}>{e>=0?'SF':'OPP'}</em><b>{fmt(b,k)}</b></div>})}</div>}
function Creator(){const {data}=useApp(); const ref=useRef(null); return <><Title k="Creator Studio" h="Export-Ready Graphics" p="Compact, branded chart frames for social and video workflows."/><div className="toolbar"><button onClick={()=>downloadSvg(ref.current,'ninervision-team-tiers.svg')}><Download size={16}/> Export SVG</button><span className="pill">Square · 16:9 · Vertical presets next</span></div><div ref={ref} className="creatorFrame"><div className="exportHead"><b>NINERVISION</b><span>49ers Intelligence · Team Tiers</span></div><TeamTierChart rows={data.league} compact/><div className="exportFoot">Data: generated public football data · NVI includes efficiency, explosiveness, pressure, and situational stability.</div></div></>}
function downloadSvg(node,name){const svg=node?.querySelector('svg'); if(!svg)return; const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); URL.revokeObjectURL(a.href);}
function DataEngine(){const {data,filters}=useApp();return <><Title k="Data Confidence" h="System Health" p="Internal validation view. Keep this out of the main story experience."/><section className="grid three"><SituationCard title="Teams" value={data.league.length} desc="Expected 32."/><SituationCard title="Players" value={data.players.length} desc="SF player profile rows."/><SituationCard title="QBs" value={data.qbs.length} desc="QB comparison rows."/></section><pre className="codebox">{JSON.stringify({filters,source:data.source,teams:data.league.length,players:data.players.length,qbs:data.qbs.length},null,2)}</pre></>}

createRoot(document.getElementById('root')).render(<App/>);
